%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Iseberg-2\Documents\MATLAB\Work\Model_01\Traj_02\Debug2.dat
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/04/06 13:32:12

%% Initialize variables.
filename = 'C:\Users\Iseberg-2\Documents\MATLAB\Work\Model_01\Traj_02\Debug2.dat';

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%15f%15f%15f%15f%15f%15f%15f%15f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
t = dataArray{:, 1};
q_4 = dataArray{:, 2};
q_1 = dataArray{:, 3};
q_2 = dataArray{:, 4};
q_3 = dataArray{:, 5};
q_4_ex = dataArray{:, 6};
q_1_ex = dataArray{:, 7};
q_2_ex = dataArray{:, 8};
q_3_ex = dataArray{:, 9};

q = [q_1,q_2,q_3,q_4];
q_ex = [q_1_ex,q_2_ex,q_3_ex,q_4_ex];

%% Clear temporary variables
clearvars filename formatSpec fileID dataArray ans;